"""empty message

Revision ID: 4f7ab2fc025f
Revises: 9e6c56f71e33
Create Date: 2019-02-19 01:28:38.862002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7ab2fc025f'
down_revision = '9e6c56f71e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('pay_day', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'pay_day')
    # ### end Alembic commands ###
